sudo: false

language: c

env:
- PATH=~/racket/bin:$PATH

before_install:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- curl -L -o installer.sh http://plt.eecs.northwestern.edu/snapshots/current/installers/racket-test-current-x86_64-linux-precise.sh
- sh installer.sh --in-place --dest ~/racket/

install:
- racket -l- pkg/dirs-catalog --link --check-metadata pkgs-catalog .
- echo file://`pwd`/pkgs-catalog/ > catalog-config.txt
- raco pkg config catalogs >> catalog-config.txt
- raco pkg config --set catalogs `cat catalog-config.txt`
- raco pkg update -i --no-setup source-syntax/ typed-racket-lib/ typed-racket-more/ typed-racket-compatibility/ typed-racket-doc/ typed-racket/ typed-racket-test/
- raco setup typed typed-racket typed-racket-test

script:
- racket -l typed-racket-test/run -- --unit
- racket -l typed-racket-test/run -- --int
- racket -l typed-racket-test/run -- --opt
- racket -l typed-racket-test/run -- --missed-opt
- raco setup -j 1 math
- racket -l typed-racket-test/run -- --math
- echo "done"

after_script:
